pragma solidity ^0.8.20;

string constant ERR_UNSUPPORTED_CURRENCY = "UC";
string constant ERR_MISMATCH_QUOTE_CURRENCY = "MQC";
string constant ERR_INVALID_MATCHED_SIZE = "IMS";
string constant ERR_NO_TRADE_PERMISSION = "NTP";
string constant ERR_FEE_CAP_EXCEEDED = "FCE";
string constant ERR_DIV_BY_ZERO = "DIVZ";
string constant ERR_NOT_FOUND = "404";
string constant ERR_INVALID_PRICE_UPDATE = "BAD_PRICE_UPDATE";
string constant ERR_NOT_SUPPORTED = "not supported";
string constant ERR_UNSAFE_CAST = "USC";

error InvalidTimestamp();
error InvalidTxId();
error WrongKind();
error InvalidExpiry();
error SpotPriceNotUSD();
error WrongKindOrQuote();
error FundingIndexOutOfRange();
error IntervalDurationMismatch();
error FundingRateOutOfRange();
error FundingTickTooSoon();
error NotOracleSigner();
error NotMarketDataSigner();
error PayloadAlreadyExecuted();
error FundingHighConfigMissing();
error FundingLowConfigMissing();
error PriceTickExpired();
error InvalidSignatureExpiry();
error NotKUQAsset();
error EmptyMarginTiers();
error TooManyMarginTiers();
error MarginFirstBracketMustStartAtZero();
error MarginBracketNotIncreasing();
error MarginRateNotIncreasing();
error NotConfigAddress();
error MarginLockActive();
