export const CurrencyToEnum: { [cur: string]: number } = {
  UNSPECIFIED: 0,
  USD: 1,
  USDC: 2,
  USDT: 3,
  ETH: 4,
  BTC: 5,
}

export const MarginTypeToEnum: { [cur: string]: number } = {
  SIMPLE_CROSS_MARGIN: 2,
  PORTFOLIO_CROSS_MARGIN: 3,
}

export const KindToEnum: { [kind: string]: number } = {
  UNSPECIFIED: 0,
  PERPETUAL: 1,
  FUTURE: 2,
  CALL: 3,
  PUT: 4,
  SPOT: 5,
  SETTLEMENT: 6,
  RATE: 7,
}

export const ConfigIDToEnum: { [config: string]: number } = {
  UNSPECIFIED: 0,
  DEPRECATED_1: 1,
  ORACLE_ADDRESS: 2,
  CONFIG_ADDRESS: 3,
  MARKET_DATA_ADDRESS: 4,
  ADMIN_FEE_SUB_ACCOUNT_ID: 5,
  INSURANCE_FUND_SUB_ACCOUNT_ID: 6,
  FUNDING_RATE_HIGH: 7,
  FUNDING_RATE_LOW: 8,
  FUTURES_MAKER_FEE_MINIMUM: 9,
  FUTURES_TAKER_FEE_MINIMUM: 10,
  OPTIONS_MAKER_FEE_MINIMUM: 11,
  OPTIONS_TAKER_FEE_MINIMUM: 12,
  ERC_20_ADDRESSES: 13,
  L_2_SHARED_BRIDGE_ADDRESS: 14,
  SIMPLE_CROSS_FUTURES_INITIAL_MARGIN: 15,
  WITHDRAWAL_FEE: 16,
  BRIDGING_PARTNER_ADDRESSES: 17
};