name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  foundry:
    strategy:
      matrix:
        module: 
          - "./contracts"
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: none

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd ${{ matrix.module }}
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge format
        run: |
          cd ${{ matrix.module }}
          forge fmt --check
        id: formatter

      - name: Run Forge tests
        run: |
          cd ${{ matrix.module }}
          forge test -vvv
        id: forge-test

  hardhat:
    strategy:
      matrix:
          module: 
            - "./contracts"
      fail-fast: true

    name: Hardhat project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: none

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "yarn"
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Node dependencies
        run: |
          yarn install

      - name: Run Era Test Node Action
        uses: dutterbutter/era-test-node-action@latest
        with:
          mode: 'run'
          showCalls: 'user'
          showStorageLogs: 'read'
          showVmDetails: 'all'
          showGasDetails: 'all'
          resolveHashes: 'true'
          log: 'info'
          logFilePath: 'era_test_node.log'
          target: 'x86_64-unknown-linux-gnu'
          releaseTag: 'latest'

      - name: Run Hardhat tests
        run: |
          yarn prettier:check
          yarn test
        id: hardhat-test
