name: test

on:
  pull_request:

jobs:
  hardhat:
    strategy:
      matrix:
          module: 
            - "./contracts"
      fail-fast: true

    name: Hardhat project
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          submodules: recursive

      - name: Install Node dependencies
        run: |
          yarn install

      - name: Compile era contracts
        run: |
          yarn compile:era

      - name: Run Era Test Node Action
        uses: gravity-technologies/era-test-node-action@main
        with:
          mode: 'run'
          showCalls: 'user'
          showStorageLogs: 'read'
          showVmDetails: 'all'
          showGasDetails: 'all'
          log: 'info'
          target: 'x86_64-unknown-linux-gnu'
          releaseTag: v0.1.0-alpha.19
          downloadUrlOverride: 'https://github.com/matter-labs/era-test-node/releases/download/v0.1.0-alpha.19/era_test_node-v0.1.0-alpha.19-x86_64-unknown-linux-gnu.tar.gz'

      - name: Run Hardhat tests
        run: |
          yarn prettier:check
          yarn test:hardhat
        id: test-hardhat

      - name: Run Forge tests
        run: |
          cd ${{ matrix.module }}
          yarn test:forge
        id: test-forge