name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  hardhat:
    strategy:
      matrix:
          module: 
            - "./contracts"
      fail-fast: true

    name: Hardhat project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          submodules: recursive

      - name: Install Node dependencies
        run: |
          yarn install

      - name: Run Era Test Node
        uses: dutterbutter/era-test-node-action@latest
        with:
          mode: "fork"
          network: "mainnet"
          forkAtHeight: "1855248"
          showCalls: "user"
          showStorageLogs: "read"
          showVmDetails: "all"
          showGasDetails: "all"
          resolveHashes: "true"
          log: "info"
          logFilePath: "era_test_node.log"
          target: "x86_64-unknown-linux-gnu"
          releaseTag: "latest"

      - name: Run Hardhat tests
        run: |
          yarn prettier:check
          yarn test:hardhat
        id: hardhat-test

      - name: Run Forge tests
        run: |
          cd ${{ matrix.module }}
          forge test -vvv
        id: forge-test